<template><h4 id="防抖与节流"><a class="header-anchor" href="#防抖与节流">#</a> 防抖与节流:</h4>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>
<span class="token keyword">function</span> <span class="token function">throttle</span><span class="token punctuation">(</span><span class="token parameter">fn<span class="token punctuation">,</span>waittime<span class="token punctuation">,</span>immediate</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
  <span class="token keyword">let</span> perTime <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>     <span class="token comment">// 之前的时间</span>
  <span class="token keyword">let</span> context<span class="token punctuation">;</span>
  <span class="token keyword">let</span> args
  <span class="token keyword">let</span> timer <span class="token operator">=</span> <span class="token keyword">null</span>
  <span class="token keyword">return</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
   <span class="token keyword">let</span> nowTime <span class="token operator">=</span> <span class="token operator">+</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
   context <span class="token operator">=</span>  <span class="token keyword">this</span>       <span class="token comment">// 如果不缓存的话，this将指向window</span>
   args <span class="token operator">=</span> argument
  <span class="token function">clearTimeout</span><span class="token punctuation">(</span>timer<span class="token punctuation">)</span>
   <span class="token keyword">if</span><span class="token punctuation">(</span>nowTime<span class="token operator">-</span>perTime <span class="token operator">></span> immediate<span class="token punctuation">)</span> <span class="token punctuation">{</span>
   <span class="token function">func</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span>context<span class="token punctuation">,</span>args<span class="token punctuation">)</span>
   perTime <span class="token operator">=</span> nowTime
   <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
      timer <span class="token operator">=</span> <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
         timer <span class="token operator">=</span> <span class="token keyword">null</span>
         <span class="token function">fn</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span>context<span class="token punctuation">,</span>args<span class="token punctuation">)</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>waittime<span class="token punctuation">)</span>
   <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">let</span> a <span class="token operator">=</span> <span class="token number">1</span>
<span class="token keyword">function</span> <span class="token function">aa</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
   a<span class="token operator">++</span>
<span class="token punctuation">}</span>
window<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">'resize'</span><span class="token punctuation">,</span><span class="token function">throttle</span><span class="token punctuation">(</span>aa<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// 使用方式</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br></div></div><h5 id="参考链接-https-github-com-mqyqingfeng-blog-issues-26"><a class="header-anchor" href="#参考链接-https-github-com-mqyqingfeng-blog-issues-26">#</a> 参考链接：<a href="https://github.com/mqyqingfeng/Blog/issues/26" target="_blank" rel="noopener noreferrer">https://github.com/mqyqingfeng/Blog/issues/26<OutboundLink/></a></h5>
<h5 id="防抖参考链接-https-github-com-mqyqingfeng-blog-issues-22"><a class="header-anchor" href="#防抖参考链接-https-github-com-mqyqingfeng-blog-issues-22">#</a> 防抖参考链接：<a href="https://github.com/mqyqingfeng/Blog/issues/22" target="_blank" rel="noopener noreferrer">https://github.com/mqyqingfeng/Blog/issues/22<OutboundLink/></a></h5>
</template>